# Generated by Django 3.0.7 on 2020-06-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0002_auto_20200628_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinflarfanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(max_length=60, null=True)),
                ('B', models.CharField(max_length=60, null=True)),
                ('C', models.CharField(max_length=60, null=True)),
                ('answer', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
