# Generated by Django 3.0.7 on 2020-06-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0003_sinflarfanlar_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_tests.Sinflarfanlar'),
            preserve_default=False,
        ),
    ]
