# Generated by Django 3.0.7 on 2020-06-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0004_test_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinflarfanlar',
            name='fanlar',
            field=models.CharField(choices=[('Ona tili', 'Ona tili'), ('Adabiyot', 'Adabiyot'), ('Fizika', 'Fizika'), ('Algebra', 'Algebra'), ('Rus tili', 'Rus tili'), ('Kimyo', 'Kimyo'), ('Biologiya', 'Biologiya'), ('Informatika', 'Informatika'), ('Ingliz tili', 'Ingliz tili'), ('Geometriya', 'Geometriya')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinflarfanlar',
            name='sinf',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
