# Generated by Django 3.0.7 on 2020-06-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0005_auto_20200628_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='question',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
