# Generated by Django 3.0.7 on 2020-06-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0007_auto_20200629_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
