# Generated by Django 3.0.7 on 2020-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0009_auto_20200702_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='viloyat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
