# Generated by Django 3.0.7 on 2020-07-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0010_auto_20200704_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='validator',
        ),
    ]
