# Generated by Django 3.0.7 on 2020-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0013_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='add_student',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='add_test',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
