# Generated by Django 3.0.7 on 2020-07-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0014_auto_20200708_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
