# Generated by Django 3.0.7 on 2020-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0015_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
