# Generated by Django 3.0.7 on 2020-08-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0016_student_grade2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.TextField(null=True)),
                ('allow', models.BooleanField(null=True)),
            ],
        ),
    ]
