# Generated by Django 3.0.7 on 2020-08-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0017_additionaladmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaladmin',
            old_name='allow',
            new_name='allowStudent',
        ),
        migrations.AddField(
            model_name='additionaladmin',
            name='allowTest',
            field=models.BooleanField(null=True),
        ),
    ]
