# Generated by Django 3.1 on 2020-08-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0018_auto_20200816_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaladmin',
            old_name='allowStudent',
            new_name='allow',
        ),
        migrations.RemoveField(
            model_name='additionaladmin',
            name='allowTest',
        ),
    ]
