# Generated by Django 2.2.7 on 2020-09-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0019_auto_20200821_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
